### PR TITLE
Fixed DbSet property naming

### LINKED ISSUE #70: Scaffolding postgre database failed: Could not compile data connection assembly
Hello,

It seems that NP cannot compile my database: Postgre 14
If I open my postgre database in LinkPad it works (windows), if I do the same in NetPad (macos) it can't. I also tested my connection and it succeeded. Not sure what I'm missing, maybe this part is failing : https://github.com/tareqimbasher/NetPad/blob/5be4889efc4abe037934eabf7791a3ae0fb61889/src/Infrastructure/NetPad.Infrastructure/Data/EntityFrameworkCore/EntityFrameworkResourcesGenerator.cs#L231

image

```bash
[500] PATCH: http://localhost:57930/data-connections/34e80e5e-b87c-4416-b060-ddfa9e9db4e3/database-structure
```

```js
{
  details: null,
  message: "Could not compile data connection assembly. Compilation failed with the following diagnostics: \n(39,26): error CS0246: The type or namespace name 'Equipment_HIDDEN' could not be found (are you missing a using directive or an assembly reference?)"
}
```

### PR DESCRIPTION
**Pull request by jwallet**
close #70

sometimes the DbSet name is the same as the property name, which ends up altering the DbSet name by adding the suffix HIDDEN

```c#
public virtual DbSet<Employee> Employees_HIDDEN { get; set; } = null!;
public virtual DbSet<EmployeeDevice> EmployeeDevices_HIDDEN { get; set; } = null!;
 public virtual DbSet<Equipment_HIDDEN> Equipment_HIDDEN { get; set; } = null!;
```

### CODE REVIEW

File: src/Infrastructure/NetPad.Infrastructure/Data/EntityFrameworkCore/EntityFrameworkResourcesGenerator.cs [hunk 1]
```diff
@@ -2,6 +2,7 @@
 using System.Collections.Generic;
 using System.Linq;
 using System.Text;
+using System.Text.RegularExpressions;
```
Comment (jwallet) [inline src/Infrastructure/NetPad.Infrastructure/Data/EntityFrameworkCore/EntityFrameworkResourcesGenerator.cs:5]:
```suggestion
```

**Comment by tareqimbasher** [comment]
Good catch. Will review, thank you for contributing!

**Comment by tareqimbasher** [comment]
Thanks @jwallet, sorry was out of town for a few days. PR looks good.
